name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: 'readme.md'
          template: '<a href="https://github.com/{{{ login }}}"><img src="{{{ avatarUrl }}}" width="60px" alt="{{{ login }}}" /></a>&nbsp;&nbsp;'

      - name: README
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: '.'
